name: MicroWISE CI

on:
  push:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.filter.outputs.changes.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Detect changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - 'services/frontend/**'
            auth-service:
              - 'services/auth-service/**'
            account-service:
              - 'services/account/**'
  
  build:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.has_changed != '[]' }}
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.has_changed) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build ${{ matrix.service }}
        run: |
          echo "Building ${{ matrix.service }}"

